version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    env_file:
      - ./backend-api/.development.env
    volumes:
      - ./backend-api:/app
      - /app/node_modules
    ports:
      - 3000:8080
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    ports:
      - 3001:3000
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
